[theme]
primaryColor             = "#2E86C1"
backgroundColor          = "#FFFFFF"
secondaryBackgroundColor = "#F4F6F7"
textColor                = "#2C3E50"
font                     = "sans serif"

[browser]
gatherUsageStats = false
